services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: douala-drive-api
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
    command: ["npm", "start"]
    restart: always
