services:
  douala-drive-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: douala-drive-api
    ports:
      - "5020:5020"
    environment:
      NODE_ENV: production
      DB_HOST: postgres  # Référence le service PostgreSQL
      DB_PORT: 5432
      # DB_NAME: mydb
      DB_ADMIN_USERNAME: hkdigitals
      DB_ADMIN_PASSWORD: hkdigitals
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/node_modules
      - /usr/src/app/dist # Exclure ce dossier
    networks:
      - shared-network
    command: ["npm", "start"]
    restart: always

networks:
  shared-network:
    external: true  # Utiliser le réseau partagé existant
